name: 'Amplify PR Preview'
on:
  pull_request_target:
    types: [review_requested]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: set branchname env
        id: setenvname
        run: |
          # use GITHUB_HEAD_REF that is set to PR source branch
          echo "##[set-output name=setbranchname;]$(echo ${GITHUB_HEAD_REF})"

      - name: deploy PR preview
        uses: yinlinchen/amplify-preview-actions@master
        with:
          branch_name: ${{ steps.setenvname.outputs.setbranchname }}
          amplify_command: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_PREVIEW_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_PREVIEW_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AmplifyAppId: dbulrk8k44el
          AWS_REGION: 'us-east-1'